s = "Shenanigan"

print(s[:2])
print(s[4:6])
print(s[2:])
print(s[:6])
print(s[:-4])
print(s[:2] + s[4] + s[5:])
print(s.replace("eni", "a"))
print(s)
print(s[0] + s[2] + s[4] + s[6] + s[8])
print(s[0] + s[3] + s[6] + s[9])
print(s[0] + s[4] + s[8])
print(s + " Type")
print(s[:6] + "Wabbite")